In [27]:
import pandas as pd
import seaborn as sns
import plotly.express as px
pd.options.display.max_rows = 10

In [8]:
data = {
    'Name': ['Tom', 'nick', 'krish', 'jack'],
    'Age': [20, 21, 19, 18],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

df1 = pd.DataFrame(data)
print(df1)

    Name  Age      City
0    Tom   20  New York
1   nick   21    London
2  krish   19     Paris
3   jack   18     Tokyo

In [17]:
data = {
    'Show': ['Showboat', 'Rent', 'Hamilton', 'Riverdance', "Hot Way"],
    'time': ['8:00', '7:00', '6:00', '5:00', '7:00'],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Dallas']
}

df2 = pd.DataFrame(data)
print(df)

    Name  Age      City
0    Tom   20  New York
1   nick   21    London
2  krish   19     Paris
3   jack   18     Tokyo

In [ ]:
df3 = pd.merge(left=df1, right=df2, left_on="City", right_on="City", how='left')

In [ ]:
df3

In [10]:
data = {
    'Street': ['Main', 'South Way', 'River', 'Highland', '42nd', "Glee", "Oui", "Kajz"],
    'City':   ['New York', 'London', 'Paris', 'Tokyo','New York', 'London', 'Paris', 'Tokyo']
}

df3 = pd.DataFrame(data)
print(df)

    Name  Age      City
0    Tom   20  New York
1   nick   21    London
2  krish   19     Paris
3   jack   18     Tokyo

In [12]:
df4 = pd.merge(left=df2, right=df3, left_on="City", right_on="City", how='inner')

In [13]:
df4

         Show  time      City     Street
0    Showboat  8:00  New York       Main
1    Showboat  8:00  New York       42nd
2        Rent  7:00    London  South Way
3        Rent  7:00    London       Glee
4    Hamilton  6:00     Paris      River
5    Hamilton  6:00     Paris        Oui
6  Riverdance  5:00     Tokyo   Highland
7  Riverdance  5:00     Tokyo       Kajz

In [18]:
data = {
    'Street': ['Main', 'South Way', 'River', 'Highland', '42nd', "Glee", "Oui", "Kajz"],
    'City':   ['Newport News', 'London', 'Paris', 'Tokyo','New York', 'London', 'Paris', 'Tokyo']
}

df5 = pd.DataFrame(data)
print(df)

    Name  Age      City
0    Tom   20  New York
1   nick   21    London
2  krish   19     Paris
3   jack   18     Tokyo

In [15]:
df6 = pd.merge(left=df2, right=df5, left_on="City", right_on="City", how='inner')
df6

         Show  time      City     Street
0    Showboat  8:00  New York       42nd
1        Rent  7:00    London  South Way
2        Rent  7:00    London       Glee
3    Hamilton  6:00     Paris      River
4    Hamilton  6:00     Paris        Oui
5  Riverdance  5:00     Tokyo   Highland
6  Riverdance  5:00     Tokyo       Kajz

In [19]:
pd.merge(left=df2, right=df5, left_on="City", right_on="City", how='left')
# Dallas is only in the df2 dataframe, so it shows up, but Street, from df5 is NaN

         Show  time      City     Street
0    Showboat  8:00  New York       42nd
1        Rent  7:00    London  South Way
2        Rent  7:00    London       Glee
3    Hamilton  6:00     Paris      River
4    Hamilton  6:00     Paris        Oui
5  Riverdance  5:00     Tokyo   Highland
6  Riverdance  5:00     Tokyo       Kajz
7     Hot Way  7:00    Dallas        NaN

In [21]:
pd.merge(left=df2, right=df5, left_on="City", right_on="City", how='right')
# Newport News is only in df5, so is shows up, but with Show and time from df2 as Nan

         Show  time          City     Street
0         NaN   NaN  Newport News       Main
1        Rent  7:00        London  South Way
2    Hamilton  6:00         Paris      River
3  Riverdance  5:00         Tokyo   Highland
4    Showboat  8:00      New York       42nd
5        Rent  7:00        London       Glee
6    Hamilton  6:00         Paris        Oui
7  Riverdance  5:00         Tokyo       Kajz

In [23]:
pd.merge(left=df2, right=df5, left_on="City", right_on="City", how='outer')
# Here Dallas from df2 shows up and NewPort News from df5

         Show  time          City     Street
0     Hot Way  7:00        Dallas        NaN
1        Rent  7:00        London  South Way
2        Rent  7:00        London       Glee
3    Showboat  8:00      New York       42nd
4         NaN   NaN  Newport News       Main
5    Hamilton  6:00         Paris      River
6    Hamilton  6:00         Paris        Oui
7  Riverdance  5:00         Tokyo   Highland
8  Riverdance  5:00         Tokyo       Kajz

In [25]:
df2

         Show  time      City
0    Showboat  8:00  New York
1        Rent  7:00    London
2    Hamilton  6:00     Paris
3  Riverdance  5:00     Tokyo
4     Hot Way  7:00    Dallas

In [30]:
fig = px.bar(df2,x="Show", y="time")

In [31]:
plot_div = fig.to_html(full_html=False, include_plotlyjs='cdn')

In [32]:
plot_div

'<div>                        <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: \'local\'};</script>\n        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.3.1.min.js" integrity="sha256-4rD3fugVb/nVJYUv5Ky3v+fYXoouHaBSP20WIJuEiWg=" crossorigin="anonymous"></script>                <div id="edf5c421-e0a4-438c-8ac3-63cbdcb4f8f5" class="plotly-graph-div" style="height:100%; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("edf5c421-e0a4-438c-8ac3-63cbdcb4f8f5")) {                    Plotly.newPlot(                        "edf5c421-e0a4-438c-8ac3-63cbdcb4f8f5",                        [{"hovertemplate":"Show=%{x}\\u003cbr\\u003etime=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e","legendgroup":"","marker":{"color":"#636efa","pattern":{"shape":""}},"name":"","orientation":"v","showlegend":false,"textposition":"auto","x":["Showboat","Rent","Hamilton","Riverdance","Hot Way"],"xaxis":"x","y":["8:00","7:00","6:00","5:00","7:00"],"yaxis":"y","type":"bar"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"}}},"xaxis":{"anchor":"y","domain":[0.0,1.0],"title":{"text":"Show"}},"yaxis":{"anchor":"x","domain":[0.0,1.0],"title":{"text":"time"}},"legend":{"tracegroupgap":0},"margin":{"t":60},"barmode":"relative"},                        {"responsive": true}                    )                };            </script>        </div>'